# Generated by Django 4.2.1 on 2026-03-12 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, help_text='建议上传正方形图片，大小不超过2MB', null=True, upload_to='avatars/%Y/%m/%d', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='个人简介')),
                ('article_count', models.IntegerField(default=0, verbose_name='发布文章数')),
                ('follow_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户个人信息',
                'verbose_name_plural': '用户个人信息',
                'db_table': 'user_profile',
            },
        ),
    ]
