# Generated by Django 5.2.12 on 2026-03-25 09:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='最多50个字符', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='昵称只能包含中文、字母、数字和下划线', regex='^[\\u4e00-\\u9fa5a-zA-Z0-9_]+$')], verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, default='avatars/default_avatar.png', help_text='建议上传正方形图片，大小不超过4MB', null=True, upload_to='avatars/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.models.validate_file_size], verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入有效的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('bio', models.TextField(blank=True, help_text='最多500个字符', max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='个人简介不能包含特殊字符', regex='^[^<>{}$]*$')], verbose_name='个人简介')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='城市')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份/州')),
                ('article_count', models.IntegerField(default=0, verbose_name='发布文章数')),
                ('follow_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '用户个人信息',
                'verbose_name_plural': '用户个人信息',
                'db_table': 'user_profile',
                'ordering': ['-updated_at'],
            },
        ),
    ]
