# Generated by Django 4.2.1 on 2026-03-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='邮箱'),
        ),
    ]
