# Generated by Django 4.2.1 on 2026-03-13 08:24

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', help_text='建议上传正方形图片，大小不超过2MB', null=True, upload_to='avatars/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), users.models.validate_file_size], verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='最多500个字符', max_length=500, null=True, validators=[django.core.validators.RegexValidator(message='个人简介不能包含特殊字符', regex='^[^<>{}$]*$')], verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='最多50个字符', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='昵称只能包含中文、字母、数字和下划线', regex='^[\\u4e00-\\u9fa5a-zA-Z0-9_]+$')], verbose_name='昵称'),
        ),
    ]
