# Generated by Django 5.2.12 on 2026-03-25 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['name'], name='idx_category_name')],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('summary', models.CharField(blank=True, max_length=500, null=True, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('cover', models.ImageField(blank=True, default='avatars/default_cover.png', null=True, upload_to='article/cover/', verbose_name='封面图')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('recycle', '回收站')], default='draft', max_length=20, verbose_name='文章状态')),
                ('read_count', models.PositiveBigIntegerField(default=0, verbose_name='阅读量')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-is_top', '-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='最多500字', max_length=500, verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.article', verbose_name='关联文章')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='article.comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='article.comment', verbose_name='关联评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '评论点赞',
                'verbose_name_plural': '评论点赞',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['name'], name='idx_tag_name')],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='JuejinHotArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juejin_article_id', models.CharField(max_length=50, unique=True, verbose_name='掘金文章ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文章摘要')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI 摘要')),
                ('original_url', models.URLField(max_length=500, verbose_name='掘金原文链接')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='掘金作者')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='文章来源')),
                ('published_time', models.DateTimeField(blank=True, null=True, verbose_name='掘金发布时间')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('tags', models.ManyToManyField(blank=True, to='article.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '掘金热榜文章',
                'verbose_name_plural': '掘金热榜文章',
                'ordering': ['-crawl_time'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='article.tag', verbose_name='标签'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent', '-created_time'], name='idx_cmt_art_par_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_time'], name='idx_cmt_user_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_time'], name='idx_cmt_par_time'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['-crawl_time'], name='idx_juejin_crawl_time'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['-published_time'], name='idx_juejin_pub_time'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['author'], name='idx_juejin_author'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['source'], name='idx_juejin_source'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status', '-is_top', '-created_time'], name='idx_art_cat_stat_top_time'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status', '-created_time'], name='idx_art_auth_stat_time'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-is_top', '-published_time'], name='idx_art_stat_top_pub'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-read_count'], name='idx_art_stat_readcnt'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_time'], name='idx_art_pub_time'),
        ),
    ]
