# Generated by Django 5.2.12 on 2026-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='点赞数'),
        ),
    ]
