# Generated by Django 4.2.1 on 2026-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, default='https://picsum.photos/800/600', null=True, upload_to='article/cover/', verbose_name='封面图'),
        ),
    ]
