# Generated by Django 4.2.1 on 2026-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, default='avatars/default_cover.png', null=True, upload_to='article/cover/', verbose_name='封面图'),
        ),
    ]
