# Generated by Django 5.2.12 on 2026-04-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSDNArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csdn_article_id', models.CharField(max_length=50, unique=True, verbose_name='CSDN文章ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文章摘要')),
                ('original_url', models.URLField(max_length=500, verbose_name='CSDN原文链接')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='CSDN作者')),
                ('source', models.CharField(blank=True, default='CSDN', max_length=50, null=True, verbose_name='文章来源')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
            options={
                'verbose_name': 'CSDN文章',
                'verbose_name_plural': 'CSDN文章',
                'ordering': ['-crawl_time'],
                'indexes': [models.Index(fields=['-crawl_time'], name='idx_csdn_crawl_time'), models.Index(fields=['author'], name='idx_csdn_author'), models.Index(fields=['source'], name='idx_csdn_source')],
            },
        ),
    ]
