# Generated by Django 5.2.12 on 2026-04-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_csdnarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audit_passed',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
        migrations.AddField(
            model_name='article',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_audited',
            field=models.BooleanField(default=False, verbose_name='是否已审核'),
        ),
        migrations.AddField(
            model_name='article',
            name='violation_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='违规原因'),
        ),
        migrations.AddField(
            model_name='comment',
            name='audit_passed',
            field=models.BooleanField(default=False, verbose_name='是否审核通过'),
        ),
        migrations.AddField(
            model_name='comment',
            name='audit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_audited',
            field=models.BooleanField(default=False, verbose_name='是否已审核'),
        ),
        migrations.AddField(
            model_name='comment',
            name='violation_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='违规原因'),
        ),
    ]
