# Generated by Django 4.2.1 on 2026-03-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_commentlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='文章摘要'),
        ),
    ]
