# Generated by Django 5.2.12 on 2026-03-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuejinHotArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juejin_article_id', models.CharField(max_length=50, unique=True, verbose_name='掘金文章ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='文章摘要')),
                ('original_url', models.URLField(max_length=500, verbose_name='掘金原文链接')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='掘金作者')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='文章来源')),
                ('published_time', models.DateTimeField(blank=True, null=True, verbose_name='掘金发布时间')),
                ('crawl_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('tags', models.ManyToManyField(blank=True, to='article.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '掘金热榜文章',
                'verbose_name_plural': '掘金热榜文章',
                'ordering': ['-crawl_time'],
            },
        ),
    ]
