# Generated by Django 5.2.12 on 2026-04-28 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_article_audit_passed_article_audit_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField(verbose_name="题目")),
                ("option_a", models.CharField(max_length=255, verbose_name="选项A")),
                ("option_b", models.CharField(max_length=255, verbose_name="选项B")),
                ("option_c", models.CharField(max_length=255, verbose_name="选项C")),
                ("option_d", models.CharField(max_length=255, verbose_name="选项D")),
                ("correct_option", models.CharField(max_length=1, verbose_name="正确答案")),
                ("explanation", models.TextField(blank=True, default="", verbose_name="解析")),
                ("knowledge_point", models.CharField(blank=True, default="", max_length=120, verbose_name="知识点")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="article.article",
                        verbose_name="关联文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章测验题",
                "verbose_name_plural": "文章测验题",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["article", "-created_time"], name="idx_quiz_article_time")],
            },
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="7天学习计划", max_length=120, verbose_name="计划名称")),
                ("total_days", models.PositiveIntegerField(default=7, verbose_name="总天数")),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划",
                "verbose_name_plural": "学习计划",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="WrongQuestionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("selected_option", models.CharField(max_length=1, verbose_name="错误答案")),
                ("correct_option", models.CharField(max_length=1, verbose_name="正确答案")),
                ("knowledge_point", models.CharField(blank=True, default="", max_length=120, verbose_name="知识点")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="记录时间")),
                ("resolved", models.BooleanField(default=False, verbose_name="是否已掌握")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_records",
                        to="article.quizquestion",
                        verbose_name="错题",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题本",
                "verbose_name_plural": "错题本",
                "ordering": ["-created_time"],
                "indexes": [models.Index(fields=["user", "resolved", "-created_time"], name="idx_wrong_user_res_time")],
            },
        ),
        migrations.CreateModel(
            name="StudyPlanItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day_index", models.PositiveIntegerField(verbose_name="第几天")),
                ("target_minutes", models.PositiveIntegerField(default=20, verbose_name="目标学习分钟")),
                ("is_checked_in", models.BooleanField(default=False, verbose_name="是否已打卡")),
                ("checked_in_at", models.DateTimeField(blank=True, null=True, verbose_name="打卡时间")),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_plan_items",
                        to="article.article",
                        verbose_name="推荐文章",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="article.studyplan",
                        verbose_name="学习计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "学习计划任务",
                "verbose_name_plural": "学习计划任务",
                "ordering": ["day_index"],
                "unique_together": {("plan", "day_index")},
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("selected_option", models.CharField(max_length=1, verbose_name="用户答案")),
                ("is_correct", models.BooleanField(default=False, verbose_name="是否正确")),
                ("created_time", models.DateTimeField(auto_now_add=True, verbose_name="作答时间")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="article.quizquestion",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "作答记录",
                "verbose_name_plural": "作答记录",
                "ordering": ["-created_time"],
                "indexes": [
                    models.Index(fields=["user", "-created_time"], name="idx_attempt_user_time"),
                    models.Index(fields=["question", "user"], name="idx_attempt_q_user"),
                ],
            },
        ),
    ]
