# Generated by Django 5.2.12 on 2026-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_quizquestion_quizattempt_studyplan_studyplanitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='标签名称'),
        ),
    ]
