# Generated by Django 5.2.12 on 2026-03-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_juejinhotarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='juejinhotarticle',
            name='ai_summary',
            field=models.TextField(blank=True, verbose_name='AI 摘要'),
        ),
    ]
