# Generated by Django 5.2.12 on 2026-05-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_quizattempt_quizquestion_studyplan_and_more'),
        ('article', '0007_alter_tag_name'),
    ]

    operations = [
    ]
