# Generated by Django 5.2.12 on 2026-03-21 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_juejinhotarticle_ai_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='article_com_article_339e3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='article_com_user_id_eeec6e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name',)},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status', '-is_top', '-created_time'], name='idx_art_cat_stat_top_time'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status', '-created_time'], name='idx_art_auth_stat_time'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-is_top', '-published_time'], name='idx_art_stat_top_pub'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-read_count'], name='idx_art_stat_readcnt'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_time'], name='idx_art_pub_time'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='idx_category_name'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent', '-created_time'], name='idx_cmt_art_par_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_time'], name='idx_cmt_user_time'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_time'], name='idx_cmt_par_time'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['-crawl_time'], name='idx_juejin_crawl_time'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['-published_time'], name='idx_juejin_pub_time'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['author'], name='idx_juejin_author'),
        ),
        migrations.AddIndex(
            model_name='juejinhotarticle',
            index=models.Index(fields=['source'], name='idx_juejin_source'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='idx_tag_name'),
        ),
    ]
