# Generated by Django 5.2.12 on 2026-05-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_merge_20260518_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='audio_content_hash',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='音频内容哈希'),
        ),
        migrations.AddField(
            model_name='article',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='article/audio/', verbose_name='文章音频'),
        ),
        migrations.AddField(
            model_name='article',
            name='audio_generated',
            field=models.BooleanField(default=False, verbose_name='音频已生成'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分类名称'),
        ),
    ]
