"""
Django settings for extraordinaryblog project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from django.contrib import messages
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a2&a6h8l(4uj9w8pl9jprkwf(m5gbl17-^ipr28bx3+v@svfb#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",  # 博客核心 全局配置
    "authentication",  # 用户认证模块
    "article",  # 文章模块
    "users",  # 用户个人信息模块
    "rest_framework",  # 新增：注册 DRF
    "django_filters",  # 可选：用于 API 过滤
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'extraordinaryblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'extraordinaryblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# 静态文件配置

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

# 邮件配置 (QQ邮箱推荐的稳定版)
EMAIL_BACKEND = "extraordinaryblog.email_backend.CustomEmailBackend"
EMAIL_HOST = "smtp.qq.com"
EMAIL_PORT = 465  # 使用 SSL 加密的标准端口
EMAIL_HOST_USER = "3320841884@qq.com"
EMAIL_HOST_PASSWORD = "pigcapvpbktgcjhj"  # 确保这里是 QQ 邮箱生成的有效授权码
EMAIL_USE_SSL = True  # 明确启用 SSL
EMAIL_USE_TLS = False  # 明确禁用 TLS，避免与 SSL 冲突


REST_FRAMEWORK = {
    # 分页：全局默认分页
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # 每页显示 10 篇文章
    # 认证：支持 session + token（博客登录/鉴权用）
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",  # 适配 Django 登录
        "rest_framework.authentication.TokenAuthentication",  # 可选：token 认证（移动端用）
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT认证
    ],
    # 权限：未登录只读，登录可写（符合博客逻辑）
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # 可选：过滤、排序
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    # 可选：API 文档美化
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
}


from datetime import timedelta

SIMPLE_JWT = {
    # access_token 过期时间（15分钟）
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # refresh_token 过期时间（7天）
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # 允许刷新 token
    "ROTATE_REFRESH_TOKENS": True,
    # 刷新 token 后，旧的 refresh_token 失效
    "BLACKLIST_AFTER_ROTATION": True,
}
